    version: '3.4'

    services:
      labtest2-db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          - MSSQL_PID=Express 
          - ACCEPT_EULA=Y
          - SA_PASSWORD=${SA_PASSWORD}
      labtest2-client:
        image: labtest2-clientwebapp:vs
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_Kestrel__Certificates__Default__Password="Dragon404"
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/DevSkill.Web.pfx
          - ASPNETCORE_URLS=http://+:54381;https://+:44311;
          - ASPNETCORE_HTTPS_PORT=44331
          - ASPNETCORE_ConnectionStrings__DefaultConnection=${DefaultConnection:-Server=labtest2-db;Database=labtest2;User Id=sa;Password=${SA_PASSWORD}; Persist Security Info=true; MultipleActiveResultSet=true}
          - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
          - NODE_ENV=Development
        build:
          context: .
          dockerfile: Applications/Web/Server/Dockerfile.debug
        extra_hosts:
          - "S3WASM:172.16.1.2"
        ports:
          - "5400:80"
          - "5500:443"
        volumes:
          - ${APPDATA}/Roaming/Microsoft/UserSecrets/:/root/.microsoft/usersecrets:ro
          #- ${APPDATA}/Roaming/ASP.NET/Https:/root/.aspnet/https/:ro
          - ${APPDATA}/Roaming/mkcert:/root/.local/share/mkcert/:rw
          - ${USERPROFILE}/.nuget/packages:/root/.nuget/packages:ro
          - ${ProgramFiles}/dotnet/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages2:ro