    version: '3.4'

    services:
      labtest2-db:
        image: mcr.microsoft.com/mssql/server:2017-latest 
      labtest2-client:
        image: labtest2-clientwebapp:vs
        environment:
          - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
          - VaultUri=https://sslforfree.vault.azure.net
          - SSLPassword=rafsanssl2020
        build:
          context: .
          dockerfile: Applications/Web/Server/Dockerfile.debug
        extra_hosts:
          - "S3WASM:172.16.1.2"
        ports:
          - "5400:80"
          - "5500:443"
        volumes:
          - ${APPDATA}/Roaming/Microsoft/UserSecrets/:/root/.microsoft/usersecrets:ro
          #- ${APPDATA}/Roaming/ASP.NET/Https:/root/.aspnet/https/:ro
          - ${APPDATA}/Roaming/mkcert:/root/.local/share/mkcert/:rw
          - ${USERPROFILE}/.nuget/packages:/root/.nuget/packages:ro
          - ${ProgramFiles}/dotnet/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages2:ro